name: Build & Test (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.8.3

jobs:
  build-windows:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          arch: win64_msvc2019_64

      - name: Configure project with CMake
        run: cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build project
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure -E "QtTests|QmlTests"
          set QT_QPA_PLATFORM=offscreen
          ctest --output-on-failure -R "QtTests|QmlTests"

      - name: Package binary
        run: |
          mkdir package
          copy build\TestApp.exe package\
          7z a TestApp-windows.zip .\package\*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestApp-windows
          path: TestApp-windows.zip
