name: Build & Test (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.8.3

jobs:
  build-windows:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          arch: win64_msvc2019_64

      - name: Install Ninja
        uses: ashutoshvarma/setup-ninja@v1

      - name: Configure CMake project
        run: cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build project
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Run tests (normal tests)
        run: |
          cd build
          ctest --output-on-failure -E "QtTests|QmlTests"

      - name: Run tests (Qt/Qml tests in offscreen mode)
        run: |
          cd build
          set QT_QPA_PLATFORM=offscreen
          ctest --output-on-failure -R "QtTests|QmlTests"

      - name: Deploy Qt libraries (windeployqt)
        run: |
          & "C:\Qt\${{ env.QT_VERSION }}\msvc2019_64\bin\windeployqt.exe" build\TestApp.exe

      - name: Package executable + DLLs
        run: |
          mkdir package
          copy build\TestApp.exe package\
          copy build\*.dll package\
          7z a TestApp-windows.zip .\package\*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestApp-windows
          path: TestApp-windows.zip
