name: Build & Test (Windows - Qt 5.15.2 - MSVC)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release
  QT_VERSION: 5.15.2

jobs:
  build:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2 (MSVC2019 64-bit)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2019_64

      - name: Configure CMake project
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build project (Release)
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Run CppTests
        run: |
          cd build
          ctest --output-on-failure -C ${{ env.BUILD_TYPE }} -E "QtTests|QmlTests"

      - name: Run QtTests and QmlTests (offscreen)
        run: |
          cd build
          $env:QT_QPA_PLATFORM="offscreen"
          ctest --output-on-failure -C ${{ env.BUILD_TYPE }} -R "QtTests|QmlTests"

      - name: Package executable
        run: |
          mkdir package
          copy build\Release\TestApp.exe package\
          7z a TestApp-windows.zip .\package\*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestApp-windows
          path: TestApp-windows.zip
