name: Build and Test (Tolerant)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.5.0'  # adapte si nécessaire

    - name: Configure project
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: |
        cd build
        cmake --build . --config Release

    - name: Check executables (tolerant)
      shell: pwsh
      run: |
        if (!(Test-Path "build/Release/TestApp.exe")) {
            Write-Host "::warning::TestApp.exe not found."
        } else {
            Write-Host "TestApp.exe found."
        }
        if (!(Test-Path "build/tests/qml-tests/Release/QmlTests.exe")) {
            Write-Host "::warning::QmlTests.exe not found."
        } else {
            Write-Host "QmlTests.exe found."
        }

    - name: Run tests (tolerant)
      continue-on-error: true
      run: |
        cd build
        ctest --output-on-failure --config Release

    - name: Upload build artifacts (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: BuildArtifacts
        path: build/
