name: Build & Test (Windows - Visual Studio)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.6.3

jobs:
  build-windows:
    name: Build and Test on Windows (MSVC)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt + Qt Tools
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          arch: win64_msvc2019_64
          modules: "qttools"

      - name: Configure CMake project
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build project
        run: |
          cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Run tests (CppTest uniquement)
        run: |
          cd build
          ctest --output-on-failure -C ${{ env.BUILD_TYPE }} -E "QtTests|QmlTests"

      - name: Run tests (QtTests et QmlTests en mode offscreen)
        run: |
          cd build
          $env:QT_QPA_PLATFORM="offscreen"
          ctest --output-on-failure -C ${{ env.BUILD_TYPE }} -R "QtTests|QmlTests"

      - name: Deploy Qt libraries with windeployqt
        shell: pwsh
        run: |
          $qtBinDir = "$Env:GITHUB_WORKSPACE\Qt\6.6.3\msvc2019_64\bin"
          & "$qtBinDir\windeployqt.exe" build\Release\TestApp.exe

      - name: Package executable and DLLs
        run: |
          mkdir package
          copy build\Release\TestApp.exe package\
          copy build\Release\*.dll package\
          7z a TestApp-windows.zip .\package\*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestApp-windows
          path: TestApp-windows.zip
